[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
waki = "0.5.0"
waki-macros = "0.5.0"
wit-bindgen = "0.36.0"

[profile.release]
opt-level = "s"
