test_url := "https://api.ipify.org" # Use `just test_url="..." sometarget` to change the default URL.

build:
	cargo build --release

test:
	TEST_URL="{{ "test_url" | prepend: "{{" | append: "}}" }}" cargo test -- --ignored --nocapture

serve:
	obelisk server run

submit:
	obelisk client execution submit --follow template-http:activity/http-get.get-plain '["{{ "test_url" | prepend: "{{" | append: "}}" }}"]'

