[[activity_wasm]]
name = "{{crate_name}}"
location = "${DEPLOYMENT_DIR}/target/wasm32-wasip2/release/{{crate_name}}.wasm"
[[activity_wasm.allowed_host]]
pattern = "https://api.ipify.org"
methods = ["GET"]
[[activity_wasm.allowed_host]]
pattern = "http://localhost:8080" # Allow getting info from the Web API server
methods = ["GET"]
