[[activity_wasm]]
name = "activity_myfibo"
location = "oci://docker.io/getobelisk/example_activity_fibo_template:2026-07-13@sha256:9d6b25f81f1fa6ee5b8ff705d15fe39b530c25b0f242c337a28926f5d287cae4"

[[workflow_wasm]]
name = "{{crate_name}}"
location = "target/wasm32-unknown-unknown/release/{{crate_name}}.wasm"
backtrace.sources = {".../src/lib.rs" = "src/lib.rs"}
