api.listening_addr = "127.0.0.1:5005"   # Address and port on which the API server will listen.
webui.listening_addr = "127.0.0.1:8080" # Address and port on which the webui webhook component will listen.

[log.stdout]
enabled = true

[[activity_wasm]]
name = "activity_myfibo"
location.oci = "docker.io/getobelisk/example_activity_fibo_template:2025-09-28@sha256:70a5ca86e5d581ba5df7037a83c0fe8860802b5ac25a1e117f1c7df9965fde92"

[[workflow]]
name = "{{crate_name}}"
location.path = "${OBELISK_TOML_DIR}/target/wasm32-unknown-unknown/release/{{crate_name}}.wasm"
backtrace.sources = {"${OBELISK_TOML_DIR}/src/lib.rs" = "${OBELISK_TOML_DIR}/src/lib.rs"}
