api.listening_addr = "127.0.0.1:5005"   # Address and port on which the API server will listen.
webui.listening_addr = "127.0.0.1:8080" # Address and port on which the webui webhook component will listen.

[[activity_wasm]]
name = "activity_myfibo"
location = "oci://docker.io/getobelisk/example_activity_fibo_template:2026-03-30@sha256:d580a48e5d81b7cfc7092c06247ee8115f6ef26c4c47d9d802fb8a83849d1738"

[[workflow]]
name = "{{crate_name}}"
location = "${DEPLOYMENT_DIR}/target/wasm32-unknown-unknown/release/{{crate_name}}.wasm"
backtrace.sources = {".../src/lib.rs" = "${DEPLOYMENT_DIR}/src/lib.rs"}
