[package]
name = "http-simple-activity"
version = "0.1.0"
authors = ["Tomas Olvecky <tomas.olvecky@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
waki = "0.5.1"
wit-bindgen = "0.38.0"

[profile.release]
opt-level = "s"
