api_listening_addr = "127.0.0.1:5005"   # Address and port on which the API server will listen.
webui.listening_addr = "127.0.0.1:8080" # Address and port on which the webui webhook component will listen.

[[activity_wasm]]
name = "{{crate_name}}"
location.path = "target/wasm32-wasip2/release/{{crate_name}}.wasm"


