[[activity_wasm]]
name = "activity_myfibo"
location = "components/activity_myfibo.wasm"

[[workflow_wasm]]
name = "workflow_myfibo"
location = "components/workflow_myfibo.wasm"

[[webhook_endpoint_wasm]]
name = "{{crate_name}}"
location = "target/wasm32-wasip2/release/{{crate_name}}.wasm"
routes = [{ methods = ["GET"], route = "/fibo/:N/:ITERATIONS" }]
backtrace.sources = {".../src/lib.rs" = "src/lib.rs"}
