[[activity_wasm]]
name = "activity_myfibo"
location = "oci://docker.io/getobelisk/example_activity_fibo_template:2026-04-08@sha256:0507c0bee133edcaef50d5712397cdd376475e4c69d8b821896a0a218f7320ce"

[[workflow_wasm]]
name = "workflow_myfibo"
location = "oci://docker.io/getobelisk/example_workflow_fibo_template:2026-04-08@sha256:ac27cb6ccb5986e2d0cb129603e19ace9e63a587c298798288eb05468307bb8f"

[[webhook_endpoint_wasm]]
name = "{{crate_name}}"
location = "target/wasm32-wasip2/release/{{crate_name}}.wasm"
routes = [{ methods = ["GET"], route = "/fibo/:N/:ITERATIONS" }]
backtrace.sources = {".../src/lib.rs" = "src/lib.rs"}
