[[activity_wasm]]
name = "activity_myfibo"
location = "oci://docker.io/getobelisk/example_activity_fibo_template:2026-03-30@sha256:d580a48e5d81b7cfc7092c06247ee8115f6ef26c4c47d9d802fb8a83849d1738"

[[workflow_wasm]]
name = "workflow_myfibo"
location = "oci://docker.io/getobelisk/example_workflow_fibo_template:2026-03-30@sha256:90577177c3a5ddd0b0c439b4c14cd9e90b47b1ed418a562e4821a08fb2dbfe41"

[[webhook_endpoint_wasm]]
name = "{{crate_name}}"
location = "${DEPLOYMENT_DIR}/target/wasm32-wasip2/release/{{crate_name}}.wasm"
routes = [{ methods = ["GET"], route = "/fibo/:N/:ITERATIONS" }]
backtrace.sources = {".../src/lib.rs" = "${DEPLOYMENT_DIR}/src/lib.rs"}
