[[activity_wasm]]
name = "{{crate_name}}"
location = "target/wasm32-wasip2/release/{{crate_name}}.wasm"
[[activity_wasm.allowed_host]]
pattern = "https://api.github.com"
methods = ["POST"]
secrets = ["GITHUB_TOKEN"]
replace_in = ["headers"]
